import { useState, useEffect } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { MainLayout } from "@/layouts/MainLayout";
import { ChatLayout } from "@/components/lexi/ChatLayout";
import { UploadPanel, type UploadedFile } from "@/components/lexi/UploadPanel";
import { RightContextPanel } from "@/components/lexi/RightContextPanel";
import type { Message } from "@/components/lexi/MessageBubble";
import { ChatAPI } from "@/services/api";
import { motion } from "framer-motion";
import { FileUp } from "lucide-react";

export const Route = createFileRoute("/chat")({
  head: () => ({
    meta: [
      { title: "Chat — LexiAI" },
      { name: "description", content: "Ask questions about your legal documents with cited answers." },
    ],
  }),
  component: ChatPage,
});

function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(false);
  const [files, setFiles] = useState<UploadedFile[]>([]);
  const [showUpload, setShowUpload] = useState(false);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [currentChatTitle, setCurrentChatTitle] = useState("New Chat");
  const [isInitialized, setIsInitialized] = useState(false);

  // Load or create initial chat on mount
  useEffect(() => {
    if (!isInitialized) {
      loadOrCreateChat();
      setIsInitialized(true);
    }
  }, [isInitialized]);

  const loadOrCreateChat = async () => {
    try {
      const { chats } = await ChatAPI.listChats();
      
      if (chats.length > 0) {
        // Load most recent chat
        const recent = chats[0];
        await loadChat(recent.session_id);
      } else {
        // Create new chat if none exist
        await createNewChat();
      }
    } catch (error) {
      console.error('[ChatPage] Error loading chats:', error);
      await createNewChat();
    }
  };

  const loadChat = async (chatSessionId: string) => {
    try {
      console.log('[ChatPage] Loading chat:', chatSessionId);
      const chat = await ChatAPI.getChat(chatSessionId);
      
      setSessionId(chat.session_id);
      setCurrentChatTitle(chat.title);
      
      // Convert backend messages to frontend format
      const loadedMessages: Message[] = chat.messages.map((msg: any) => ({
        id: crypto.randomUUID(),
        role: msg.role,
        content: msg.content,
        createdAt: new Date(msg.timestamp).getTime(),
      }));
      
      setMessages(loadedMessages);
      console.log('[ChatPage] Loaded', loadedMessages.length, 'messages');
    } catch (error) {
      console.error('[ChatPage] Error loading chat:', error);
    }
  };

  const createNewChat = async () => {
    try {
      const response = await ChatAPI.createChat();
      setSessionId(response.session_id);
      setCurrentChatTitle("New Chat");
      setMessages([]);
      console.log('[ChatPage] Created new chat:', response.session_id);
      return response.session_id;
    } catch (error) {
      console.error('[ChatPage] Error creating chat:', error);
      return null;
    }
  };

  // Debug: Log session ID changes
  const handleSessionId = (id: string) => {
    console.log('[ChatPage] Session ID received:', id);
    setSessionId(id);
  };

  const send = async (text: string) => {
    console.log('[ChatPage] Sending message. Session ID:', sessionId);
    
    if (!sessionId) {
      const botMsg: Message = {
        id: crypto.randomUUID(),
        role: "assistant",
        content: "Please upload documents first before asking questions.",
        createdAt: Date.now(),
      };
      setMessages((m) => [...m, botMsg]);
      return;
    }

    const userMsg: Message = {
      id: crypto.randomUUID(),
      role: "user",
      content: text,
      createdAt: Date.now(),
    };
    setMessages((m) => [...m, userMsg]);
    setLoading(true);
    
    try {
      const { answer, sources } = await ChatAPI.send(text, sessionId);
      const botMsg: Message = {
        id: crypto.randomUUID(),
        role: "assistant",
        content: answer,
        createdAt: Date.now(),
        citations: sources?.map((s: any) => ({ label: s.source, page: s.page })),
      };
      setMessages((m) => [...m, botMsg]);
      
      // Auto-update title after first message
      if (messages.length === 0 && currentChatTitle === "New Chat") {
        // Title will be auto-generated by backend
        // Refresh chat list to get updated title
        setTimeout(async () => {
          try {
            const { chats } = await ChatAPI.listChats();
            const current = chats.find(c => c.session_id === sessionId);
            if (current) {
              setCurrentChatTitle(current.title);
            }
          } catch (e) {
            console.error('Error refreshing title:', e);
          }
        }, 500);
      }
    } catch (err: any) {
      console.error('[ChatPage] Error sending message:', err);
      const errorMessage = err?.detail || err?.message || "Failed to get response";
      const errMsg: Message = {
        id: crypto.randomUUID(),
        role: "assistant",
        content: `Error: ${errorMessage}`,
        createdAt: Date.now(),
      };
      setMessages((m) => [...m, errMsg]);
    } finally {
      setLoading(false);
    }
  };

  const regenerate = (id: string) => {
    setMessages((prev) => {
      const idx = prev.findIndex((m) => m.id === id);
      if (idx <= 0) return prev;
      const prompt = prev[idx - 1]?.content;
      if (!prompt) return prev;
      const trimmed = prev.slice(0, idx);
      setLoading(true);
      setTimeout(() => {
        setMessages((m) => [
          ...m,
          {
            id: crypto.randomUUID(),
            role: "assistant",
            content: `Regenerated answer for "${prompt}":\n\nA fresh perspective with refined clause references and risk highlights.`,
            createdAt: Date.now(),
            citations: files[0] ? [{ label: files[0].name, page: 5 }] : undefined,
          },
        ]);
        setLoading(false);
      }, 800);
      return trimmed;
    });
  };

  return (
    <MainLayout
      title="AI Legal Assistant"
      subtitle="RAG-grounded legal analysis"
      activeChatId={sessionId || undefined}
      onNewChat={createNewChat}
      onSelectChat={loadChat}
      rightSlot={<RightContextPanel files={files} onFilesChange={setFiles} onSessionId={handleSessionId} />}
    >
      <div className="relative flex-1 flex flex-col min-h-0">
        {/* Floating upload toggle (mobile/tablet) */}
        <div className="xl:hidden border-b border-border px-4 py-2 flex items-center justify-between glass-strong">
          <div className="text-xs text-muted-foreground">
            {files.length > 0 ? `${files.length} document(s)` : "No documents uploaded"}
            {sessionId && <span className="ml-2 text-success">✓ Ready</span>}
          </div>
          <button
            onClick={() => setShowUpload((s) => !s)}
            className="inline-flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg glass hover:border-primary/40 transition-colors"
          >
            <FileUp className="h-3.5 w-3.5" /> {showUpload ? "Hide" : "Upload"}
          </button>
        </div>

        {showUpload && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            className="xl:hidden border-b border-border p-4 bg-surface/40"
          >
            <UploadPanel files={files} onChange={setFiles} onSessionId={handleSessionId} />
          </motion.div>
        )}

        {/* Desktop: side-by-side chat + uploads on the left of context panel */}
        <div className="flex-1 flex min-h-0">
          <div className="flex-1 min-w-0">
            <ChatLayout
              messages={messages}
              loading={loading}
              onSend={send}
              onRegenerate={regenerate}
            />
          </div>
        </div>
      </div>
    </MainLayout>
  );
}
